import type { Portfolio, Fund } from "../types";

export const SAMPLE_FUNDS: Fund[] = [
  {
    id: "f1",
    name: "Mirae Asset Large Cap Fund",
    category: "large_cap",
    investedAmount: 200000,
    currentValue: 248000,
    nav: 98.45,
    units: 2519,
    returns1Y: 18.2,
    returns3Y: 14.5,
    returns5Y: 16.8,
    riskLevel: "moderately_high",
    expenseRatio: 0.54,
    aum: 35420,
    benchmark: "Nifty 100",
    manager: "Neelesh Surana",
    aiRecommendation: { action: "hold", confidence: 78, rationale: "Strong large-cap fundamentals, aligned with market momentum." },
  },
  {
    id: "f2",
    name: "Axis Midcap Fund",
    category: "mid_cap",
    investedAmount: 150000,
    currentValue: 201000,
    nav: 78.2,
    units: 1919,
    returns1Y: 24.1,
    returns3Y: 20.3,
    returns5Y: 22.1,
    riskLevel: "high",
    expenseRatio: 0.63,
    aum: 22180,
    benchmark: "Nifty Midcap 150",
    manager: "Shreyash Devalkar",
    aiRecommendation: { action: "reduce", confidence: 65, rationale: "Overweight mid-cap at 26% of portfolio. Consider trimming 5-8%.", targetAllocation: 18 },
  },
  {
    id: "f3",
    name: "SBI Small Cap Fund",
    category: "small_cap",
    investedAmount: 100000,
    currentValue: 152000,
    nav: 134.6,
    units: 742,
    returns1Y: 31.8,
    returns3Y: 26.2,
    returns5Y: 28.5,
    riskLevel: "very_high",
    expenseRatio: 0.74,
    aum: 18930,
    benchmark: "BSE 250 SmallCap",
    manager: "R Srinivasan",
    aiRecommendation: { action: "hold", confidence: 71, rationale: "Outstanding long-term returns but high volatility. Maintain for long-term goals." },
  },
  {
    id: "f4",
    name: "HDFC Balanced Advantage Fund",
    category: "hybrid",
    investedAmount: 200000,
    currentValue: 224000,
    nav: 452.3,
    units: 442,
    returns1Y: 12.8,
    returns3Y: 11.2,
    returns5Y: 13.6,
    riskLevel: "moderate",
    expenseRatio: 0.82,
    aum: 61250,
    benchmark: "NIFTY 50 Hybrid Composite",
    manager: "Chirag Setalvad",
    aiRecommendation: { action: "hold", confidence: 84, rationale: "Strong risk-adjusted returns. Provides good downside protection." },
  },
  {
    id: "f5",
    name: "Nippon India Index Fund - Nifty 50",
    category: "index",
    investedAmount: 100000,
    currentValue: 118000,
    nav: 28.4,
    units: 3521,
    returns1Y: 14.2,
    returns3Y: 13.8,
    returns5Y: 14.9,
    riskLevel: "moderately_high",
    expenseRatio: 0.2,
    aum: 11240,
    benchmark: "Nifty 50",
    manager: "Mehul Dama",
    aiRecommendation: { action: "buy", confidence: 88, rationale: "Lowest cost market exposure. Consider increasing allocation for long-term core holding." },
  },
  {
    id: "f6",
    name: "ICICI Pru Short Term Debt Fund",
    category: "debt",
    investedAmount: 100000,
    currentValue: 107500,
    nav: 56.8,
    units: 1761,
    returns1Y: 7.2,
    returns3Y: 6.8,
    returns5Y: 7.1,
    riskLevel: "low",
    expenseRatio: 0.44,
    aum: 14320,
    benchmark: "NIFTY Short Duration",
    manager: "Manish Banthia",
    aiRecommendation: { action: "hold", confidence: 79, rationale: "Stable debt allocation provides portfolio cushion during market volatility." },
  },
];

export const SAMPLE_PORTFOLIO: Portfolio = {
  id: "p1",
  userId: "demo",
  name: "My Growth Portfolio",
  createdAt: "2022-01-15",
  updatedAt: new Date().toISOString(),
  funds: SAMPLE_FUNDS,
  totalInvested: 850000,
  currentValue: 1050500,
  returns: 200500,
  returnsPercent: 23.59,
  healthScore: 72,
  riskScore: 64,
};
